## TITANIC

In [1]:
import os #path handling
import numpy as np #import numpy drives sklearn to use numpy arrays instead of python lists
import pandas as pd #CSV and dataframe handling
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier #kNN classifier
from sklearn.model_selection import train_test_split #Data set splitting functions
from sklearn.metrics import confusion_matrix #Confusion matrix
#Needed for SGD
from sklearn.linear_model import SGDClassifier 
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
#Needed for linear classification
from sklearn.svm import LinearSVC
#Needed for neural network
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_digits
from sklearn.metrics import classification_report

In [4]:
dataPath = './' # path to folder containing the Iris data
dataFile = os.path.join(dataPath,'titanic.csv') # data file to use

In [5]:
# we assign column names based on the description file. 'FType' stands for 'Flower Type'
fullDF = pd.read_csv(dataFile,header=None,names=['Age','Cabin','Enbarked','Fare','Name','Parch','Passengerld','Pclass','Sex','SibSP','Survived','Ticket']) 
fullDF.sample(10) # let's take a random sample from the full data frame

,Age,Cabin,Enbarked,Fare,Name,Parch,Passengerld,Pclass,Sex,SibSP,Survived,Ticket
884,38.0,NaN,S,7.05,"Goncalves, Mr. Manuel Estanslas",0,466,3,male,0,0,SOTON/O.Q. 3101306
407,23.0,NaN,S,10.5,"Ware, Mr. William Jeffery",0,1298,2,male,1,0,28666
1092,31.0,NaN,S,13.0,"Wilhelms, Mr. Charles",0,674,2,male,0,1,244270
1230,39.0,NaN,S,24.15,"Lester, Mr. James",0,812,3,male,0,0,A/4 48871
49,60.0,D15,C,76.2917,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",0,940,1,female,0,1,11813
838,10.0,NaN,S,24.15,"Van Impe, Miss. Catharina",2,420,3,female,0,0,345773
768,42.0,NaN,S,8.6625,"Dimic, Mr. Jovan",0,350,3,male,0,0,315088
1030,NaN,NaN,S,7.05,"Jardin, Mr. Jose Neto",0,612,3,male,0,0,SOTON/O.Q. 3101305
530,14.5,NaN,C,14.4542,"Zabour, Miss. Hileni",0,112,3,female,1,0,2665
1151,NaN,NaN,S,0.0,"Knight, Mr. Robert J",0,733,2,male,0,0,239855

In [6]:
fullDF.describe() # quick statistical description of the dataframe

,Age,Cabin,Enbarked,Fare,Name,Parch,Passengerld,Pclass,Sex,SibSP,Survived,Ticket
count,1047,296,1308,1309,1310,1310,1310,1310,1310,1310,1310,1310
unique,99,187,4,282,1308,9,1310,4,3,8,3,930
top,24.0,C23 C25 C27,S,8.05,"Kelly, Mr. James",0,PassengerId,3,male,0,0,CA. 2343
freq,47,6,914,60,2,1002,1,709,843,891,815,11

In [10]:
def dataMap(Sex):

    label = 0

    if Sex == 'male':
        label = 0
    elif Sex == 'female':
        label = 1
    else:
        raise(RuntimeWarning(f'Unknown sex: {Sex}, using default label 0'))
    
    return label

In [11]:
# Let's apply the mapping function to the input data and create a new column called 'Y'
fullDF['Y'] = [dataMap(item) for item in fullDF['Sex']]

RuntimeWarning: Unknown sex: Sex, using default label 0

In [ ]:
# Let's check that mapping works on a few random samples
fullDF.sample(10)

In [ ]:
dataDF = fullDF[['sepalL','sepalW','petalL','petalW']]
classDF = fullDF['Y']

In [ ]:
# Let's split the data into training data, and test data. Same splitting should be applied to classes.
# Here, the test data size is 10% of the full dataset
trainData,testData,trainY,testY = train_test_split(dataDF,classDF,test_size=0.1)